### PR TITLE
Fail gracefully

### PR DESCRIPTION
**Pull request by ilapros**
This should hopefully make the package fail gracefully - as per CRAN policy. Notice I already updated the description and news file to facilitate the submission to CRAN.

### CODE REVIEW

**Comment by ilapros** [comment]
updated the .*ignore files to avoid merge conflicts

**Comment by cvitolo** [comment]
Thanks @ilapros, it looks very neat!

Travis failed because .travis.yml needed some changes. I sorted that out. Would you mind to update your PR?

**Comment by ilapros** [comment]
check if this works after travis is updated

**Comment by ilapros** [comment]
Looks like it's working now?

**Comment by cvitolo** [comment]
codecov is failing now... any idea?

**Comment by ilapros** [comment]
Well the modifications add lines which are not tested for - but I am not sure how to test for the API to fail/throw unknown errors. So yes - the changes increase the number of lines which are not tested for I imagine?

**Pull request merged**
